# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PID_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from control import step_response

import control
import os
import matlab
import matplotlib.pyplot as plt
import control
import numpy
import numpy as np
import sys

from control import step_response
from control.matlab import *
from mpmath import *



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 755)
        MainWindow.setStyleSheet("background-color: rgb(0, 85, 127);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 431, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 681, 16))
        self.label_7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 441, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 241, 51))
        self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(100, 280, 261, 20))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(450, 310, 121, 63))
        self.label_13.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(450, 380, 121, 63))
        self.label_14.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(450, 460, 131, 63))
        self.label_15.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 570, 121, 41))
        self.pushButton.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.showplot)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 570, 121, 41))
        self.pushButton_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
                                      "background-color: rgb(0, 255, 255);\n"
                                      "background-color: rgb(0, 255, 0);")
        self.pushButton_3.setObjectName("pushButton")
        self.pushButton_3.clicked.connect(self.tune_pid)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 570, 121, 41))
        self.pushButton_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 255, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.autotune)

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 310, 401, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setStyleSheet("color: rgb(0, 0, 0);")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.valueChanged.connect(self.kp_slider)
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.valueChanged.connect(self.ki_slider)
        self.horizontalLayout_4.addWidget(self.horizontalSlider_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_3.valueChanged.connect(self.kd_slider)
        self.horizontalLayout_5.addWidget(self.horizontalSlider_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def showplot(self):
        num=self.lineEdit.text()
        den=self.lineEdit_2.text()
        a = num.split()
        intnum = []
        for element in a:
            intnum.append(int(element))

        b = den.split()
        intden = []
        for element in b:
            intden.append(int(element))

        cal = control.tf(intnum,intden)
        sisotool(cal)
        plt.grid()
        plt.show()

    def kp_slider(self):
        kp=self.horizontalSlider.value()
        self.label_13.setText(str(kp))

    def ki_slider(self):
        ki = self.horizontalSlider_2.value()
        self.label_14.setText(str(ki))

    def kd_slider(self):
        kd = self.horizontalSlider_3.value()
        self.label_15.setText(str(kd))

    def tune_pid(self):
        num = self.lineEdit.text()
        den = self.lineEdit_2.text()
        a = num.split()
        intnum = []
        for element in a:
            intnum.append(int(element))

        b = den.split()
        intden = []
        for element in b:
            intden.append(int(element))

        kp = self.horizontalSlider.value()
        self.label_13.setText(str(kp))
        ki = self.horizontalSlider_2.value()
        self.label_14.setText(str(ki))

        kd = self.horizontalSlider_3.value()
        self.label_15.setText(str(kd))
        num_con=[kd,kp,ki]
        den_con=[1,0]
        tf_con=control.tf(num_con,den_con)
        cal = control.tf(intnum, intden)
        total_tf=cal*tf_con
        sisotool(total_tf)
        plt.grid()
        plt.show()

    def autotune(self):

        kd=0
        num = self.lineEdit.text()
        den = self.lineEdit_2.text()
        a = num.split()
        intnum = []
        for element in a:
            intnum.append(int(element))

        b = den.split()
        intden = []
        for element in b:
            intden.append(int(element))

        cal = control.tf(intnum, intden)

        p = stepinfo(cal)

        ki = p['RiseTime'] / 4
        kp = 1 / p['SteadyStateValue']

        num_con = [kp, ki]
        den_con = [1, 0]

        tf_con = control.tf(num_con, den_con)

        total_tf = cal * tf_con

        sisotool(total_tf)
        plt.grid()
        plt.show()
        self.label_13.setText(str(kp))
        self.label_14.setText(str(ki))
        self.label_15.setText(str(kd))




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PID controller design"))
        self.label.setText(_translate("MainWindow", "Numerator="))
        self.label_2.setText(_translate("MainWindow", "["))
        self.label_3.setText(_translate("MainWindow", "]"))
        self.label_7.setText(_translate("MainWindow", "Please insert the Numerator and Denominator of the Transfer function:"))
        self.label_4.setText(_translate("MainWindow", "Denominator="))
        self.label_5.setText(_translate("MainWindow", "["))
        self.label_6.setText(_translate("MainWindow", "]"))
        self.label_8.setText(_translate("MainWindow", "e.g: s^2+2s-1=1   2   -1"))
        self.label_12.setText(_translate("MainWindow", "PID parameter calibration:"))
        self.pushButton.setText(_translate("MainWindow", "Show Plot"))
        self.pushButton_2.setText(_translate("MainWindow", "Autotune"))
        self.pushButton_3.setText(_translate("MainWindow", "Tune"))
        self.label_9.setText(_translate("MainWindow", "Kp"))
        self.label_10.setText(_translate("MainWindow", "Ki"))
        self.label_11.setText(_translate("MainWindow", "Kd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
